const cars = [
    {
        _id: "1",
        imageUrl: "",
        name: "BMW 5 Series Sedan",
        price: "₹ 27,00,000",
        year: "2015",
        type: "SUV",
        fuel: "Electric",
        kmRunned: "57,000",
        transmission: "Manual",
        owners: "1",
        millage: "15KM",
        insured: "Yes",
        wishlisted: true
    },
    {
        _id: "2",
        imageUrl: "",
        name: "Veloster Jsn",
        price: "₹15,00,000",
        year: "2018",
        type: "SUV",
        fuel: "Petrol",
        kmRunned: "1,12,000",
        transmission: ["Manual","Auto"],
        owners: "1",
        millage: "10KM",
        insured: "Yes",
        wishlisted: false
    },
    {
        _id: "3",
        imageUrl: "",
        name: "Ford GT 130",
        price: "₹ 21,00,000",
        year: "2017",
        type: "SUV",
        fuel: "Electric",
        kmRunned: "75,000",
        transmission: "manual",
        owners: "1",
        millage: "10KM",
        insured: "No",
        wishlisted: false
    },
    {
        _id: "4",
        imageUrl: "",
        name: "Aston Martin",
        price: "15,00,000",
        year: "2016",
        type: "SUV",
        fuel: "Diesel",
        kmRunned: "50,000",
        transmission: "Auto",
        owners: "1",
        millage: "13KM",
        insured: "Yes",
        wishlisted: true
    },
    {
        _id: "5",
        imageUrl: "",
        name: "Toyato Innova",
        price: "7,00,000",
        year: "2012",
        type: "SUV",
        fuel: "Petrol",
        kmRunned: "80,000",
        transmission: "Manual",
        owners: "1",
        millage: "13KM",
        insured: "No",
        wishlisted: false
    },
    {
        _id: "6",
        imageUrl: "",
        name: "Aston Martin",
        price: "15,00,000",
        year: "2016",
        type: "SUV",
        fuel: "Diesel",
        kmRunned: "50,000",
        transmission: "Auto",
        owners: "1",
        millage: "13KM",
        insured: "Yes",
        wishlisted: true
    }
]

export default cars;